services:
  mk8dx-api:
    container_name: mk8dx-api
    image: ghcr.io/mk8dx-yuzu/mk8dx-api:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./logs:/app/logs
      - /srv/yuzu-share:/app/data # permissions must be configured
    env_file:
      - .env
  #watchtower:
  #  image: containrrr/watchtower
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --interval 120 --cleanup # check every 2 minutes
  #  restart: unless-stopped